package ir.company.app.domain.entity;

/**
 * Created by farzad on 8/13/17.
 */
public enum EPolicy {
    PER_GAME,FRIEND_GAME, INVITE, VIDEO, NEW_USER, INVITED, WIN_EXP, LOSE_EXP, DRAW_EXP, DOUBLE_WIN_EXP, DOUBLE_LOSE_EXP, WIN_PRIZE, LOSE_PRIZE, DRAW_PRIZE, DOUBLE_WIN_PRIZE, DOUBLE_LOSE_PRIZE
}
